# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    templating.engine.pug:
        class: Pug\PugSymfonyEngine
        arguments: ["@kernel", "@templating.helper.assets", "@templating.helper.router", "@templating.helper.actions"]
